#! /bin/sh
#  _                                 
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh
$HOME/.config/picom.conf

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        3
bspc config window_gap          12
bspc config border_radius

bspc config split_ratio          0.52
bspc config borderless_monocle   true
#bspc config gapless_monocle      true
bspc config single_monocle	 true
bspc config ignore_ewmh_focus	 true

#bspc config focused_border_color "#dedbd9"
bspc config focused_border_color "#65b3f7"
bspc config normal_border_color "#0c576e"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

compton --backend glx --paint-on-overlay --vsync opengl-swc &
pkill -9 xwinwrap
animbg&


